Repository Warcraft-3-Risk/wc3-risk-system, pull requests merged in 2025-03, with the labels that each got.

#87 Add template .env for MacOS to README
  README.md
Labels: documentation

#88 Update country names #63
  src/configs/city-country-setup.ts
Labels: enhancement, good first issue

#96 Enable restart when only one human player is present
  src/app/commands/restart.ts
  src/app/game/game-mode/base-game-mode.ts/game-loop-state.ts
  src/app/game/game-mode/mode/promode-mode.ts
  src/app/game/game-mode/mode/standard-mode.ts
  src/app/player/player-manager.ts
  src/app/utils/map-info.ts
Labels: enhancement

#97 Fixed on city capture and attempt at fixing shuffled player list
  src/app/game/game-mode/capital-game-mode/capitals-game-loop-state.ts
  src/app/game/game-mode/mode/capitals-mode.ts
  src/app/game/game-mode/state/base-state.ts
Labels: enhancement

#98 Added credits to microhive and roflmaooo
  src/app/quests/quests.ts
Labels: documentation, enhancement

#99 Adding support for giving yourself gold when you are the sole human i…
  src/app/commands/gold.ts
Labels: enhancement

#109 Fixed issue related to players not leaving
  src/app/game/game-mode/utillity/on-player-status.ts
Labels: bug

#114 Fixed trees having too much HP
  src/app/game/game-mode/base-game-mode.ts/setup-state.ts
Labels: bug

#115 112 capitals fix issue in which players can steal capitals of their allies
  src/app/city/city.ts
  src/app/city/land-city.ts
  src/app/city/port-city.ts
  src/app/game/event-coordinator.ts
  src/app/game/game-mode/base-game-mode.ts/countdown-state.ts
  src/app/game/game-mode/base-game-mode.ts/game-loop-state.ts
  src/app/game/game-mode/base-game-mode.ts/setup-state.ts
  src/app/game/game-mode/capital-game-mode/capitals-distribute-capitals-state.ts
  src/app/game/game-mode/capital-game-mode/capitals-game-loop-state.ts
  src/app/game/game-mode/capital-game-mode/capitals-game-loop.state.ts
  src/app/game/game-mode/capital-game-mode/capitals-reset-state.ts
  src/app/game/game-mode/capital-game-mode/capitals-selection-state.ts
  src/app/game/game-mode/state/base-state.ts
  src/app/teams/team.ts
  src/app/triggers/spell-effect-event.ts
  src/app/utils/events/event-constants.ts
  src/app/utils/map-info.ts
  src/main.ts
Labels: bug

#116 Prevent allies from capturing your base
  src/app/city/city.ts
  src/app/city/port-city.ts
  src/app/triggers/leave-region-event.ts
Labels: enhancement

#120 Player team number is now randomized
  src/app/scoreboard/team-board.ts
  src/app/teams/team-manager.ts
  src/app/teams/team.ts
  src/app/utils/utils.ts
Labels: enhancement

#123 Moved capital reset to land-city and fixed reset-state not removing a…
  src/app/city/land-city.ts
  src/app/game/game-mode/base-game-mode.ts/reset-state.ts
  src/app/game/game-mode/capital-game-mode/capitals-reset-state.ts
  src/app/game/game-mode/mode/capitals-mode.ts
  src/app/utils/map-info.ts
Labels: bug
